[technote]
id = "SQR-085"
series_id = "SQR"
canonical_url = "https://sqr-085.lsst.io"
github_url = "https://github.com/lsst-sqre/sqr-085"
github_default_branch = "main"
date_created = 2024-01-30T20:20:26Z
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[technote.status]
state = "draft"

[[technote.authors]]
name.given = "Angelo"
name.family = "Fausti"
internal_id = "faustinetoa"
orcid = "https://orcid.org/0000-0002-8095-305X"
[[technote.authors.affiliations]]
name = "Rubin Observatory Project Office"
internal_id = "RubinObs"
address = "950 N. Cherry Ave., Tucson, AZ  85719, USA"
